pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        id 'fabric-loom' version providers.gradleProperty('loom_version').get()
        id 'com.modrinth.minotaur' version '2.+'
    }
}

include("addons:ores-compat")
